# Generated by Django 5.2.12 on 2026-04-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="contact_number",
            field=models.CharField(default=12345, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Processing", "Processing"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
