# Generated by Django 5.2.12 on 2026-04-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="units",
            name="name",
        ),
        migrations.AddField(
            model_name="units",
            name="type",
            field=models.CharField(default="unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="units",
            name="value",
            field=models.CharField(default="1", max_length=100),
            preserve_default=False,
        ),
    ]
